version: '3.8'

services:
  adminer:
    image: adminer
    container_name: adminer_ui
    restart: always
    ports:
      - "8082:8080"

  postgres:
    image: postgres
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_DB: sslvdatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
