server:
  port: 8083
spring:
#  sql:
#    init:
#      mode: always
  application: name=ss-lv-scraping-service
  datasource:
    url: jdbc:postgresql://localhost:5432/sslvdatabase
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
#    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update   # or 'create' if you want recreate DB every time

#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect # Specify dialect for hibernate and Spring Boot JPA should use to connect
##    show-sql: true # print queries that are executed to console
#    hibernate:
#      ddl-auto: update # do not delete tables and columns but add in addition, not used for H2 Database(always new)
#  datasource:
#    url: jdbc:h2:mem:testdb # Try to connect this URL
#    driver-class-name: org.h2.Driver # H2 DB Driver name
#    username: sa
#    password: password
#  h2:
#    console:
#      enabled: true # Should be "True" to connect this DB on /h2-console
#
#
